### ISSUE TITLE
请问哪里可以找到您关于EWR-PGD的论文？

### ISSUE THREAD

**Issue by igeng** [liuye6666/EWR-PGD#1]
刘哥您好，我是在天池看到您的文章，我想请问您关于EWR-PGD的论文在哪里可以看到？谢谢您!

**Comment by liuye6666** [comment]
还在写，请稍等，发出来了会给出链接！

**Comment by igeng** [comment]
> 还在写，请稍等，发出来了会给出链接！

OK，感谢，祝顺利！
